plugins {
    id "com.android.application"
}

android {
    namespace "com.hanlp.nerdemo"
    compileSdk 34

    defaultConfig {
        applicationId "com.hanlp.nerdemo"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    packaging {
        resources {
            excludes += ["META-INF/*"]
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.9.0"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation "org.tensorflow:tensorflow-lite:2.13.0"
}
